# Generated by Django 5.2.8 on 2025-11-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike')], max_length=10)),
                ('upto_2_hours', models.IntegerField()),
                ('two_to_four_hours', models.IntegerField()),
                ('full_day', models.IntegerField()),
                ('monthly_pass', models.IntegerField()),
                ('parking_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='parking.parkingsite')),
            ],
        ),
        migrations.CreateModel(
            name='OptionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('parking_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_charges', to='parking.parkingsite')),
            ],
        ),
    ]
